name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Ajusta según la versión que uses en tu proyecto

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build # Genera los archivos estáticos en la carpeta "build"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build # Carpeta donde se generan los archivos para producción
